### ISSUE TITLE
Support automatic activation of profiles per environment

### ISSUE THREAD

**Issue by omallo** [microconfig/microconfig#45] opened 2021-07-15 10:32 UTC
Microconfig has really great support for overwriting configuration per environment or profile.

For profiles, one always has to explicitly state which profile should be used when importing a dependency or when using a placeholder. This is very flexible but in some cases, you might have a profile which is used on different shared components and you want this profile to always be "activated" across all components for a given environment.

As a concrete example, in our project we try to limit non-functional configurations (memory, cpu, connection pool sizes, etc.) to 2 possible configurations, one "standard" configuration and one "production mode" configuration. For that, we defined a "prodmode" profile on different shared components and we would like to always activate that profile on all the environments which should use the production mode. In order to do that, we currently have to create a separate configuration file for all our application components for the production mode environments and specify all the imports with the given profile. This needs to be done for each configuration type ("app", "helm", etc.) which is feasible but not very convenient.

I know that instead of using a profile, I could also explicitly list all the production mode environments in my configuration files (something like "application.\<env1>.\<env2>.yaml") but this is also not very convenient since I have to list the same set of environments on all files. Furthermore, in our project, we have a very large number of environments (21!).

The above is why I would like to request a feature which allows it to define one or more profiles which are automatically activated for a given environment. I think those profiles could be defined inside the environment descriptor. Microconfig would then always pick up configuration files for those profiles when building that environment. The profile specific configuration should probably be read before any environment specific configuration and the different profiles should be read in the order in which they are defined inside the environment descriptor.

I hope that my explanation above is clear enough.

Please let me know if the feature request is something you think makes sense to be supported by Microconfig.

**Comment by kapodes** [comment] 2021-07-15 13:21
@omallo 21 environments sounds really cool, can you please join our slack? we would love to chat with you and know a bit more about your setup.

**Comment by omallo** [comment] 2021-07-15 21:12
@kapodes , indeed it's a bit special with 21 environments. We are implementing an integration platform for a customer and we have around 20 services which are used by different client applications and we integrate with different backend systems. Since the client and backend systems all have their own lifecycle, the customer has many different environments for doing end-to-end testing of our services with the different client/backend systems, often with different versions of the involved systems and also with different data constellations.

Unfortunately, I do not have a slack account, sorry.

**Comment by alxmatorin** [comment] 2021-07-19 18:38
@omallo the feature is really cool and has been requested several times in our slack. But there are a lot of corner cases with this approach. We'll think a little bit more how to implement it in the best way.

**Comment by kapodes** [comment] 2021-07-26 15:00
@omallo I was thinking of introducing "parent-child" envs.

To explain let's assume you have general `dev` environment that contains general configurations applicable to all `dev` environments. But you have more than one `dev` environment, like multiple regions or multiple clients. Let's call them `dev-a` and `dev-b`.

My idea is to allow "parent-child" relationships which are described in `envs` descriptors. So you can specify `dev` as "parent" env for `dev-a` and `dev-b`

So now you can generate your configurations for `dev-a` and it will apply all `dev` general config values and override them with `dev-a` specific configs values.

Will this approach solve your issue?

**Comment by omallo** [comment] 2021-07-28 09:11
@kapodes , thanks a lot for your feedback and your work on this topic.

The use case you're describing makes totally sense to me, even though I think it's conceptually a bit different from the one I have.

In my case, I have the following profiles as an example:
- `no-security`: Disables the security in our applications and when accessing our backend systems.
- `prod-data`: Configures the logging and some functional aspects of our application for environments which have productive data.
- `prod-sizing`: Enables production sizing for things like parallelization settings, memory/cpu limits, connection pool sizes, etc.

Each of the profiles applies to several components and is used in several environments. For a given environment, I would like to be able to activate any combination of those profiles by specifying them in the `envs` descriptor.

So instead of a "parent-child" relation between actual environments (which I assume would be one-to-many?), it's more like associating one or more profiles (and maybe also environments to also cover your use case) to a given environment.

**Comment by kapodes** [comment] 2021-07-28 09:39
@omallo I don't like idea of specifying profile on env level as it will be applied to all components and can produce unexpected overrides.
What if you use sub-envs for components where you want to apply a specific profile and just explicitly put profile in `#include component[profile]` ?

Let's imagine that you have a service `foo` and you want to include some security setting to it.
so it's `application.yaml` can have
```
#include security-settings
```

but for specific dev env you want to disable your security by using a profiled include so you can do
`application.dev-a.yaml`

```
#include security-settings[no-security]
```

In this case you can just generate your configs for `dev-a` and get all expected profiles on expected components. This way it's more explicit.

Is it applicable to your use case?

**Comment by omallo** [comment] 2021-07-28 11:00
@kapodes in our case it's actually the intention to have a profile which is included throughout a whole environment across all components, so this is the semantics we want. This is conceptually similar to Spring profiles which can be activated on an environment. With Spring, you would activate the profiles at runtime and ship the configuration of the different profiles with your code. The idea would be to achieve the same but have all the configuration outside of the application code, managed by Microconfig.

You're right that I could use profile specific includes instead. This is how I started but this had the following inconveniences:
- I had to often create environment specific component configuration files just to include the desired profile of other components. This leads to many additional files I would otherwise not have to create.
- It's not immediately visible that a given environment consistently includes a specific profile.

This is the reason why I didn't use profile specific includes since it started getting a bit repetitive and error prone. Instead, the approach I'm taking right now is that I define flags as `#var`'s for enabling/disabling the profile for a given environment. I have a single file per environment which contains those flags for the different profiles and inside the component configuration files, I use Spring EL to set the correct value based on the flags. This way, I have only 1 environment specific file and no extra files for the components (but have to use Spring EL instead). This works quite fine so far.

So I do currently have an approach for solving my problem and I would also have the options of profile specific includes or just using pure Spring profiles at runtime to achieve the same, each with its own pros/cons.

**Comment by kapodes** [comment] 2021-07-28 12:34
But if you want to apply same settings on your whole env why you can't just then create a environment specific override for those settings?
Like you have service foo including some `security-settings` 
```
foo/application.yaml
include security-settings
```

and your security settings have security turned off for `dev`
```
security-settings/

application.yaml
====
security: on
===

application.dev.yaml
===
security: off
===
```

In this case you don't need to use profiles at all and just env is enough. Or this is not applicable for you?

**Comment by omallo** [comment] 2021-07-28 13:13
@kapodes this approach would also work just fine and I had also tried it. It's actually better than the approach with the profile specific includes since I only have to create additional files per profile where needed.

The only thing which disturbed me with that approach is that, since we have a large number of environments, I would have to include the same set of environment names on different configuration files across different components.

For each of the 3 mentioned profiles, we have around 7 environments on which the profiles should be activated and the combination of profiles is not always the same. So I would have 3 sets of environments which I would have to include multiple times in file names across different components.

To be honest, the problem I'm facing might be a bit specific to our case since we have many environments and I would like to avoid having to create unnecessary files or repeating the same set of environment names in files. However, as you mentioned, Microconfig already provides mechanisms for solving the problem which work great with a "reasonable" number of environments and in our case it only has the drawback of incurring some repetition, but they still work fine. So it would be fine for me if you say that it's not worth providing specific support for such a "special case" in Microconfig.

**Comment by kapodes** [comment] 2021-07-28 15:39
@omallo well having a lot of environments should not be a problem. Whole point of Microconfig is simplifying managing config at scale.
I understood your reasoning and it seems having profiles specified for an environment actually makes sense.
I think in this case we can use sub-envs and profiles together.

So you can have base `dev` environment.
More specific `dev-a` enrivonment.
Profile `foo` applied to `dev-a`.

So when you generate your config for a component and specify `dev-a` environment your config will be build with `dev` as base, then overridden with `dev-a` sub-env and then with `foo` profile values.

Approach like this would allow any number of environments to be managed in pretty simple fashion.

**Comment by alxmatorin** [comment] 2021-08-01 12:27
@omallo We've implemented the profile feature. Now you can specify a list of components that will be included in every env components.  Microconfigs will add these profiles to the end of component's includes(for example, if your service includes a,b and profiles are c,d - the order of includes is a,b,c,d)

The syntax in env files:
```
profiles:
  - standard-microservice 
  - timeouts[long]  #you can specify component profile name or env. Works exactly like standard includes
  - security[disabled]

We haven't tested this feature yet, cause maybe it's not something you wanted or not very convenient to use. So the behavior can be changed.
Could you please clone `profile` brach and test this feature, especially different corner cases? If everything is ok we will merge the code to the master and build new mc release

**Comment by alxmatorin** [comment] 2021-08-01 15:08
Small remark. Right now you can specify components with profiles in the "include" section. Not just profiles. Probably profiles instead of component+profile make more sense.

**Comment by alxmatorin** [comment] 2021-08-01 16:15
@omallo Changed the behavior. Right now you can specify a list of profiles (not components + profile). And if the top-level component or included components have profile overrides - these overrides will be added to the result file.

**Comment by omallo** [comment] 2021-08-02 20:27
@alxmatorin thanks a lot for the implementation. I was away the last couple of days but will have a look at it tomorrow. In any case, having just profiles and not components+profiles also makes more sense to me. I will provide you feedback once I did some tests.

**Comment by omallo** [comment] 2021-08-03 14:57
@alxmatorin I tried using the new profile functionality and stumbled upon a problem which seems to happen also when doing normal includes of a component profile with the released version of Microconfig.

I should mention that I'm currently using a "special" component called `vars` where I define some metadata per environment. Inside that component, I have one base configuration and one override per environment. The `vars` component is never included but I just reference individual configuration items inside my actual service components (through `${vars@...}`).

Now, when I import a component profile, then the environment specific overrides of the `vars` component are not considered anymore. I created a minimal example which shows the issue. I have the following component files with a single service:
```
common/application.yaml:
value: ${vars@value}

===
service/application.yaml:
#include common[foo]

===
vars/vars.yaml:
value: default value

===
vars/vars.dev.yaml:
value: value from dev env
```

When generating the configuration, I would expect to get `value: value from dev env`. This is not the case when I include `common[foo]`. It actually is the case when I include `common` w/o a profile.

I think that the dev specific configuration of the `vars` component should always be considered?

**Comment by alxmatorin** [comment] 2021-08-03 15:52
@omallo Do I understand correctly that you build `service` for dev env and expect 
1)`value: default value` if you #include common[foo] to `service` and common[foo] profile doesnt exist. (the current behavior is correct)
2)`value: value from dev env` if you #include common (the current behaviour is incorrect: `value: default value`)
?
The second case does not work if dev env has any profile specified and works without profiles?

**Comment by omallo** [comment] 2021-08-03 16:13
@alxmatorin yes, I build `service` for the `dev` environment.

I would actually expect to get `value: value from dev env` in both cases since the `foo` profile of the `common` component is not overriding that value. I haven't included any specific `common/application.foo.yaml` file contents since I think that this is not relevant, as long as it does not override the `value` property. Do you agree?

I'm attaching the files I'm using: [microconfig-test.zip](https://github.com/microconfig/microconfig/files/6925572/microconfig-test.zip)

The problem is reproducible independently from the new profile functionality so you can also test it with the latest released Microconfig version.

**Comment by alxmatorin** [comment] 2021-08-03 16:29
@omallo The example you attached works correctly.
The current behavior with  `#include common[foo]` is by design and has not been affected by the new profile functionality. You can try to build your configs using the last mc release(4.4.3) and the output will be the same.
if you build configs for dev end and #include common[foo] - you will get `common` values not for dev env but for 'foo'.
`common[foo]` has `${vars@value}` - it the same as ${vars[foo]@value}. vars doesnt contain vars.foo.yaml - BUT it contains default application.values - so values for foo profile will be taken from application.yaml - and you'll get 'value: default value'
If there is not application.yaml if `foo` dir then MC can't resolve ${vars[foo]@value} event if `foo` contains values in application.dev.yaml.

**Comment by alxmatorin** [comment] 2021-08-03 16:32
@omallo But there is another bug. If we build dev config for `service` and `service` #include common the result is correct: `value: value from dev env`
But if we specify dev env profile, that doesnt exist - the result is incorrect `value: value from dev env`
Just fixed.

**Comment by omallo** [comment] 2021-08-03 17:05
@alxmatorin yes, the behavior is the same with the mc release 4.4.3.

However, I personally would have expected that the configuration of the environment for which the configuration is being built is **always** considered. Even if a specific profile of a component is included, I think that any environment specific configuration should still be considered and the profile specific one should overwrite it.

Let's e.g. assume that I have a database component named `db` and I have the following configuration files:
```
db/application.yaml:
pool.maxConnections: 10

===
db/application.dev.yaml:
host: my-dev-db.com
username: dev-user
password: dev-secret

===
db/application.large.yaml:
pool.maxConnections: 50
```

Let's say I'm building the configuration for the `dev` environment and inside my service component, I want to include the "large" profile of the `db` component since that service needs more connections to the database than other services (this is not related to the `dev` environment but to the specific service). How would I do that w/o "loosing" the configuration inside the `db/application.dev.yaml` file?

**Comment by alxmatorin** [comment] 2021-08-03 17:31
@omallo if you `#include some-service[dev]` - you probably expect that you will get exactly the same configs if you build ` some-service` for `dev` env. The semantic of #include for profiles and env is the same. So the current behavior is correct and can't be changed because of backward compatibility. It's not very obvious, but your approach is not obvious either :)

I understand your case and probably what you want can be implemented with a new syntax like `#include common[+large]`.
`+` means - get `common` configs with the following priority: 1) default 2) current 3)large

`+` can be used to specify several profiles:
`#include common[test+large]` - without current, just test + large
`#include common[+test+large]` current + test + large

Right now without this syntax you can include special components with configs for profile. For example `large-db`
![image](https://user-images.githubusercontent.com/7472651/128059846-55fe8f45-11c6-474f-ab9a-61df68d2129e.png)
large-db/application.yaml
```
#include db
pool.maxConnections: 50

```

**Comment by omallo** [comment] 2021-08-03 20:27
@alxmatorin thanks for your explanations and also for the idea of using special "sub-components" to achieve the desired effect. That was helpful :)

I understand your explanation and also the fact that you cannot just change the behaviour since this would be a breaking change. I'm still having a hard time though to see a case in which you would not want any config of the current environment to be included during the build.

In any case, based on the behaviour you describe, I did some further tests, also with multiple profiles and different cases work as you describe. I found one example though which might not be correct. Let's have the following files:
```
common/application.yaml:
value: default

===
common/application.foo.yaml:
value: foo

===
service/application.yaml:
#include common

===
envs/dev.yaml:
all:
  components:
    - service
profiles:
  - foo
  - bar
```

In this case, two profiles are activated while only the `foo` profile exists on the `common` component (the `bar` profile might exist on other components). I would expect to get `value: foo` as a result but instead I get `value: default`.

**Comment by alxmatorin** [comment] 2021-08-03 20:48
@omallo This is a bug. Fixed. Thank you for the example :)

**Comment by omallo** [comment] 2021-08-03 21:12
@alxmatorin thanks to you for the fix :) Works fine now.

**Comment by alxmatorin** [comment] 2021-08-18 08:14
@omallo Have you tested all your cases? Can we merge the code and build the release?

**Comment by omallo** [comment] 2021-08-18 13:59
@alxmatorin , I hadn't realized that you were waiting for additional feedback from my side. Sorry for that.

Yes, the test cases I have all work as expected. There was the one point we had discussed about including the environment specific config also when a profile specific config is imported but I would say that this is a different topic.

So from my point of view the functionality of this issue could be merged. Thanks!

**Closed** 2021-08-18 17:25 UTC
Labels: enhancement
